---
apiVersion: v1
kind: Service
metadata:
  name: demo-blue-svc
  namespace: blue-green
  labels:
    app: demo-blue
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 8080
      name: http
  selector:
    app: demo-blue
